### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by punkpeye** [szeider/mcp-solver#2]
I'm trying to start this server so I can mark the associated [listing](https://glama.ai/mcp/servers/3qc9kfqhzb) as tested.

### Current Behavior

This is my `Dockerfile`:

```Dockerfile
FROM python:3.10

RUN pip install uv

WORKDIR /app

RUN git clone https://github.com/szeider/mcp-solver .



RUN uv sync

CMD ["uv", "run", "mcp-solver"]
```

When I run it, I get the following error:

```
/app/.venv/lib/python3.10/site-packages/minizinc/__init__.py:26: RuntimeWarning: MiniZinc was not found on the system. No default driver could be initialised.
  warnings.warn(
Traceback (most recent call last):
  File "/app/.venv/bin/mcp-solver", line 8, in <module>
    sys.exit(main())
  File "/app/src/mcp_solver/server.py", line 277, in main
    asyncio.run(serve())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/src/mcp_solver/server.py", line 19, in serve
    model_mgr = ModelManager()
  File "/app/src/mcp_solver/model_manager.py", line 22, in __init__
    self.solver = Solver.lookup(solver_name)
  File "/app/.venv/lib/python3.10/site-packages/minizinc/solver.py", line 135, in lookup
    assert driver is not None
AssertionError

```

Is there a way to install all dependencies using `uv sync` here?

### Expected Behavior

The server should start correctly when using `uv run`.

### Suggested Improvement

Could you provide a complete example in the README showing how to start the server using uv run?

This would improve usability for devel

**Comment by szeider** [comment]
Thanks for reaching out! From the error message, it looks like the issue is that MiniZinc, a required external dependency for the MCP Solver, is not installed or accessible in your environment. While uv sync sets up Python dependencies, MiniZinc needs to be installed separately.

Here are some suggestions to resolve the issue:

- Make sure MiniZinc is installed and available in the environment where you're running the solver.
- If you're using Docker, you might need to add a step in your Dockerfile to install MiniZinc.
- On macOS or Linux systems, you can use a package manager like Homebrew or apt to install MiniZinc directly.
- Once MiniZinc is installed, try re-syncing the environment with uv sync and starting the server again with uv run mcp-solver.

Let me know how it goes or if you need further help!

**Comment by szeider** [comment]
Thanks for the report. v3.x replaced the single `mcp-solver` entry point with per-mode entry points (`mcp-solver-mzn`, `mcp-solver-z3`, `mcp-solver-pysat`, `mcp-solver-maxsat`, `mcp-solver-asp`) and split extras, so users no longer pull in MiniZinc to use other modes — the traceback you posted references paths that no longer exist. We're not planning to ship a Dockerfile; please see INSTALL.md for the current setup. Closing as superseded.
